<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class IncidentReport extends Model
{
    use HasFactory;
    protected $fillable = [
       'addedby',
       'addeddate',
       'department',
       'area',
       'report_no',
       'incident_type',
       'injuredperson',
       'empid',
       'hospital',
       'incidentplace',
       'incidentdate',
       'emplyoer',
       'trade_or_occupation',
       'incidentdesc',
       'actions',
       'local_regulation',
       'eval',
       'pubrec',
       'probablity',
       'finloss',
       'efcom',
       'humtur',
       'potloss',
       'sevpotloss',
       'porbocc',
       'time',
       'reviewed_at',
       'reviewed_by',
       'reviewed',
       'justification',
       'riskassessment',
       'riskassess',
       'toolbox',
       'tooldate',
       'training',
       'traindate',
       'autherised',
       'activity',
       'investigatordisc',
       'bodypart',
       'unsafework',
       'unsafeact',
       'ppkit',
       'prevent',
       'rootcause',
       'corrective_act',
       'currective_targdate',
       'responsiblity',
       'severity',
       'further_investigate',
       'investigation_status',
       'workunsafe',
       'actunsafe',
       'attachmentby_reporter',
       'attachmentby_reviewer',
       'improve_justification',
       'adder_email',
       'improve_investigation',
       'attachmentby_investigator',
       'approver_name',
       'approver_email',
       'reviewer_name',
       'reviewer_email',
       'approved_rej',
       'rej_reason',
       'corr_implement_status'
    ];
}
